import type { Food } from "./types";
import { validateDataset } from "./compute";
import { MICROS } from "./micros";

/**
 * Baked-in nutrition dataset (spec §2/§3). Values are per 100 g, sourced from USDA
 * FoodData Central (Foundation Foods and SR Legacy where available; a few Branded
 * entries only where no generic exists — protein powders, bone broth). Every food
 * records its source `fdcId` and `fdcDataType` so each number is traceable and
 * verifiable. The client bundle contains no API key and makes no nutrition calls.
 *
 * To re-verify / refresh these values against the live FDC API, run:
 *   FDC_API_KEY=your_key npm run build:data
 * (see scripts/build-dataset.ts). The key is build-time only and never ships.
 *
 * weightBasis is per-category (spec §5): raw for muscle meats/fish, cooked for
 * legumes/grains, as sold for dairy/eggs/tofu/powders/cured/canned. Liquid densities
 * (g/mL) are approximate (spec §6) and used only for the fl-oz conversion.
 */

const POWDER_NOTE =
  "Brand-dependent; USDA generic is an approximation — your product's label will differ.";

// Macro/metadata rows. Per-100g micronutrients live in lib/micros.ts (keyed by id)
// and are attached below, so this array stays readable and the two concerns can be
// refreshed independently by the build job.
const FOOD_BASE: Omit<Food, "micros">[] = [
  // ── Poultry (basis: raw) ──────────────────────────────────────────────────
  {
    id: "chicken-breast-skinless-raw",
    name: "Chicken breast, skinless",
    category: "Poultry",
    proteinPer100g: 22.5,
    caloriesPer100g: 120,
    fatPer100g: 2.62,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171077",
    fdcDataType: "SR Legacy",
    note: "Meat only.",
  },
  {
    id: "chicken-thigh-skinless-raw",
    name: "Chicken thigh, skinless",
    category: "Poultry",
    proteinPer100g: 19.66,
    caloriesPer100g: 121,
    fatPer100g: 4.14,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173627",
    fdcDataType: "SR Legacy",
    note: "Meat only. FDC also has a fattier boneless-skinless-thigh entry (2646171) — verify via build:data.",
  },
  {
    id: "chicken-thigh-skin-on-raw",
    name: "Chicken thigh, skin-on",
    category: "Poultry",
    proteinPer100g: 16.52,
    caloriesPer100g: 221,
    fatPer100g: 16.61,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172385",
    fdcDataType: "SR Legacy",
    note: "Meat and skin.",
  },
  {
    id: "chicken-drumstick-skinless-raw",
    name: "Chicken drumstick, skinless",
    category: "Poultry",
    proteinPer100g: 20.59,
    caloriesPer100g: 119,
    fatPer100g: 3.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173614",
    fdcDataType: "SR Legacy",
    note: "Meat only.",
  },
  {
    id: "chicken-wing-raw",
    name: "Chicken wing",
    category: "Poultry",
    proteinPer100g: 17.5,
    caloriesPer100g: 191,
    fatPer100g: 12.8,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172390",
    fdcDataType: "SR Legacy",
    note: "Meat and skin.",
  },
  {
    id: "ground-chicken-93-7-raw",
    name: "Ground chicken, 93/7",
    category: "Poultry",
    proteinPer100g: 19.6,
    caloriesPer100g: 150,
    fatPer100g: 6.3,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "2278952",
    fdcDataType: "Branded",
    note: "Brand-dependent (93/7); USDA has no generic 93/7 entry. Generic SR Legacy ground chicken is ≈143 kcal / 17.4 g protein.",
  },
  {
    id: "turkey-breast-skinless-raw",
    name: "Turkey breast, skinless",
    category: "Poultry",
    proteinPer100g: 19.8,
    caloriesPer100g: 97,
    fatPer100g: 1.98,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174515",
    fdcDataType: "SR Legacy",
    note: "Retail parts, meat only.",
  },
  {
    id: "ground-turkey-93-7-raw",
    name: "Ground turkey, 93/7",
    category: "Poultry",
    proteinPer100g: 18.73,
    caloriesPer100g: 150,
    fatPer100g: 8.34,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172850",
    fdcDataType: "SR Legacy",
  },
  {
    id: "duck-breast-raw",
    name: "Duck breast, skinless",
    category: "Poultry",
    proteinPer100g: 18.28,
    caloriesPer100g: 135,
    fatPer100g: 5.95,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172410",
    fdcDataType: "SR Legacy",
    note: "USDA \"duck, domesticated, meat only, raw\" (all cuts).",
  },

  // ── Pork (basis: raw, except cured) ───────────────────────────────────────
  {
    id: "pork-tenderloin-raw",
    name: "Pork tenderloin",
    category: "Pork",
    proteinPer100g: 20.95,
    caloriesPer100g: 109,
    fatPer100g: 2.17,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168249",
    fdcDataType: "SR Legacy",
    note: "Separable lean only.",
  },
  {
    id: "pork-loin-chop-raw",
    name: "Pork loin chop",
    category: "Pork",
    proteinPer100g: 21.9,
    caloriesPer100g: 127,
    fatPer100g: 3.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168237",
    fdcDataType: "SR Legacy",
    note: "Center loin, separable lean only; fdcId inferred — verify via build:data.",
  },
  {
    id: "pork-shoulder-raw",
    name: "Pork shoulder",
    category: "Pork",
    proteinPer100g: 17.3,
    caloriesPer100g: 236,
    fatPer100g: 18.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "167843",
    fdcDataType: "SR Legacy",
    note: "Whole, separable lean and fat.",
  },
  {
    id: "ground-pork-raw",
    name: "Ground pork",
    category: "Pork",
    proteinPer100g: 16.88,
    caloriesPer100g: 263,
    fatPer100g: 21.19,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "167902",
    fdcDataType: "SR Legacy",
  },
  {
    id: "bacon-raw",
    name: "Bacon",
    category: "Pork",
    proteinPer100g: 12.62,
    caloriesPer100g: 417,
    fatPer100g: 39.69,
    carbsPer100g: 1.28,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168277",
    fdcDataType: "SR Legacy",
    note: "Cured, unprepared — high fat, will surface as inefficient (kept intentionally). Weigh as sold.",
  },
  {
    id: "ham-cured-as-sold",
    name: "Ham, sliced (cured)",
    category: "Pork",
    proteinPer100g: 16.6,
    caloriesPer100g: 163,
    fatPer100g: 8.6,
    carbsPer100g: 3.83,
    fiberPer100g: 1.3,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173864",
    fdcDataType: "SR Legacy",
    note: "Regular, ~11% fat, cured/cooked. Listed fiber (1.3 g) reflects added ingredients.",
  },

  // ── Beef (basis: raw) ─────────────────────────────────────────────────────
  {
    id: "ground-beef-90-10-raw",
    name: "Ground beef, 90/10",
    category: "Beef",
    proteinPer100g: 20.0,
    caloriesPer100g: 176,
    fatPer100g: 10.0,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174030",
    fdcDataType: "SR Legacy",
  },
  {
    id: "ground-beef-80-20-raw",
    name: "Ground beef, 80/20",
    category: "Beef",
    proteinPer100g: 17.17,
    caloriesPer100g: 254,
    fatPer100g: 20.0,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174036",
    fdcDataType: "SR Legacy",
  },
  {
    id: "beef-top-sirloin-raw",
    name: "Top sirloin, lean",
    category: "Beef",
    proteinPer100g: 22.1,
    caloriesPer100g: 131,
    fatPer100g: 4.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174055",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
  },
  {
    id: "beef-ribeye-raw",
    name: "Ribeye, lean",
    category: "Beef",
    proteinPer100g: 21.9,
    caloriesPer100g: 154,
    fatPer100g: 7.4,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172143",
    fdcDataType: "SR Legacy",
    note: "Boneless, lip-off, separable lean only.",
  },
  {
    id: "beef-flank-raw",
    name: "Flank steak, lean",
    category: "Beef",
    proteinPer100g: 21.72,
    caloriesPer100g: 143,
    fatPer100g: 6.29,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174776",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 0\" fat.",
  },
  {
    id: "beef-chuck-raw",
    name: "Chuck, lean",
    category: "Beef",
    proteinPer100g: 21.96,
    caloriesPer100g: 139,
    fatPer100g: 5.05,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174051",
    fdcDataType: "SR Legacy",
    note: "Arm pot roast, separable lean only.",
  },
  {
    id: "beef-tenderloin-raw",
    name: "Tenderloin, lean",
    category: "Beef",
    proteinPer100g: 22.12,
    caloriesPer100g: 153,
    fatPer100g: 6.52,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171812",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
  },
  {
    id: "beef-top-round-raw",
    name: "Top round, lean",
    category: "Beef",
    proteinPer100g: 22.9,
    caloriesPer100g: 135,
    fatPer100g: 4.03,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171816",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
  },

  // ── Seafood (basis: raw, except canned) ───────────────────────────────────
  {
    id: "salmon-atlantic-farmed-raw",
    name: "Salmon, Atlantic (farmed)",
    category: "Seafood",
    proteinPer100g: 20.42,
    caloriesPer100g: 208,
    fatPer100g: 13.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175167",
    fdcDataType: "SR Legacy",
  },
  {
    id: "salmon-sockeye-wild-raw",
    name: "Salmon, sockeye (wild)",
    category: "Seafood",
    proteinPer100g: 22.25,
    caloriesPer100g: 131,
    fatPer100g: 4.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173691",
    fdcDataType: "SR Legacy",
    note: "FDC entry is \"salmon, sockeye, raw\"; sockeye is wild-caught.",
  },
  {
    id: "tuna-yellowfin-raw",
    name: "Tuna, yellowfin",
    category: "Seafood",
    proteinPer100g: 24.4,
    caloriesPer100g: 109,
    fatPer100g: 0.49,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175159",
    fdcDataType: "SR Legacy",
  },
  {
    id: "tuna-canned-water-drained",
    name: "Tuna, canned in water",
    category: "Seafood",
    proteinPer100g: 25.51,
    caloriesPer100g: 116,
    fatPer100g: 0.82,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173709",
    fdcDataType: "SR Legacy",
    note: "Light, canned in water, drained solids.",
  },
  {
    id: "cod-atlantic-raw",
    name: "Cod, Atlantic",
    category: "Seafood",
    proteinPer100g: 17.81,
    caloriesPer100g: 82,
    fatPer100g: 0.67,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171955",
    fdcDataType: "SR Legacy",
  },
  {
    id: "tilapia-raw",
    name: "Tilapia",
    category: "Seafood",
    proteinPer100g: 20.08,
    caloriesPer100g: 96,
    fatPer100g: 1.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175176",
    fdcDataType: "SR Legacy",
  },
  {
    id: "shrimp-raw",
    name: "Shrimp",
    category: "Seafood",
    proteinPer100g: 13.61,
    caloriesPer100g: 71,
    fatPer100g: 1.01,
    carbsPer100g: 0.91,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "15149",
    fdcDataType: "SR Legacy",
    note: "Mixed species; current FDC entry reflects moisture-retention additives, so protein reads lower than plain shrimp.",
  },
  {
    id: "halibut-raw",
    name: "Halibut",
    category: "Seafood",
    proteinPer100g: 18.56,
    caloriesPer100g: 91,
    fatPer100g: 1.33,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174200",
    fdcDataType: "SR Legacy",
    note: "Atlantic and Pacific.",
  },
  {
    id: "sardines-canned-oil-drained",
    name: "Sardines, canned in oil",
    category: "Seafood",
    proteinPer100g: 24.62,
    caloriesPer100g: 208,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175139",
    fdcDataType: "SR Legacy",
    note: "Atlantic, drained solids with bone.",
  },
  {
    id: "mackerel-atlantic-raw",
    name: "Mackerel, Atlantic",
    category: "Seafood",
    proteinPer100g: 18.6,
    caloriesPer100g: 205,
    fatPer100g: 13.89,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175119",
    fdcDataType: "SR Legacy",
  },
  {
    id: "rainbow-trout-farmed-raw",
    name: "Rainbow trout (farmed)",
    category: "Seafood",
    proteinPer100g: 19.94,
    caloriesPer100g: 141,
    fatPer100g: 6.18,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173717",
    fdcDataType: "SR Legacy",
  },
  {
    id: "scallops-raw",
    name: "Scallops",
    category: "Seafood",
    proteinPer100g: 12.06,
    caloriesPer100g: 69,
    fatPer100g: 0.49,
    carbsPer100g: 3.18,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174220",
    fdcDataType: "SR Legacy",
    note: "Mixed species.",
  },
  {
    id: "mussels-raw",
    name: "Mussels, blue",
    category: "Seafood",
    proteinPer100g: 11.9,
    caloriesPer100g: 86,
    fatPer100g: 2.24,
    carbsPer100g: 3.69,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174216",
    fdcDataType: "SR Legacy",
  },
  {
    id: "crab-raw",
    name: "Crab, blue",
    category: "Seafood",
    proteinPer100g: 18.06,
    caloriesPer100g: 87,
    fatPer100g: 0.92,
    carbsPer100g: 0.04,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174204",
    fdcDataType: "SR Legacy",
  },

  // ── Eggs & dairy (basis: as sold) ─────────────────────────────────────────
  {
    id: "whole-egg",
    name: "Whole egg",
    category: "Eggs & dairy",
    proteinPer100g: 12.56,
    caloriesPer100g: 143,
    fatPer100g: 9.51,
    carbsPer100g: 0.72,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171287",
    fdcDataType: "SR Legacy",
  },
  {
    id: "egg-white-liquid",
    name: "Egg white (liquid)",
    category: "Eggs & dairy",
    proteinPer100g: 10.9,
    caloriesPer100g: 52,
    fatPer100g: 0.17,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.04,
    isCompleteProtein: true,
    fdcId: "172183",
    fdcDataType: "SR Legacy",
  },
  {
    id: "greek-yogurt-nonfat",
    name: "Greek yogurt, nonfat",
    category: "Eggs & dairy",
    proteinPer100g: 10.19,
    caloriesPer100g: 59,
    fatPer100g: 0.39,
    carbsPer100g: 3.6,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170894",
    fdcDataType: "SR Legacy",
  },
  {
    id: "greek-yogurt-2pct",
    name: "Greek yogurt, 2%",
    category: "Eggs & dairy",
    proteinPer100g: 9.95,
    caloriesPer100g: 73,
    fatPer100g: 1.92,
    carbsPer100g: 3.94,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170903",
    fdcDataType: "SR Legacy",
    note: "USDA \"lowfat\" Greek yogurt (~1.9% milkfat).",
  },
  {
    id: "cottage-cheese-lowfat",
    name: "Cottage cheese, low-fat",
    category: "Eggs & dairy",
    proteinPer100g: 12.39,
    caloriesPer100g: 72,
    fatPer100g: 1.02,
    carbsPer100g: 2.72,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173417",
    fdcDataType: "SR Legacy",
    note: "1% milkfat.",
  },
  {
    id: "cottage-cheese-fullfat",
    name: "Cottage cheese, full-fat",
    category: "Eggs & dairy",
    proteinPer100g: 11.12,
    caloriesPer100g: 98,
    fatPer100g: 4.3,
    carbsPer100g: 3.38,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172179",
    fdcDataType: "SR Legacy",
    note: "Creamed, large or small curd.",
  },
  {
    id: "cheddar",
    name: "Cheddar",
    category: "Eggs & dairy",
    proteinPer100g: 22.87,
    caloriesPer100g: 404,
    fatPer100g: 33.31,
    carbsPer100g: 3.09,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173414",
    fdcDataType: "SR Legacy",
  },
  {
    id: "mozzarella-part-skim",
    name: "Mozzarella, part-skim",
    category: "Eggs & dairy",
    proteinPer100g: 23.75,
    caloriesPer100g: 295,
    fatPer100g: 19.78,
    carbsPer100g: 5.58,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171244",
    fdcDataType: "SR Legacy",
    note: "Low moisture, part-skim.",
  },
  {
    id: "parmesan",
    name: "Parmesan",
    category: "Eggs & dairy",
    proteinPer100g: 35.75,
    caloriesPer100g: 392,
    fatPer100g: 25.83,
    carbsPer100g: 3.22,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170848",
    fdcDataType: "SR Legacy",
    note: "Hard.",
  },
  {
    id: "string-cheese-part-skim",
    name: "String cheese",
    category: "Eggs & dairy",
    proteinPer100g: 23.75,
    caloriesPer100g: 295,
    fatPer100g: 19.78,
    carbsPer100g: 5.58,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171244",
    fdcDataType: "SR Legacy",
    note: "String cheese is low-moisture part-skim mozzarella; same USDA generic as \"Mozzarella, part-skim\".",
  },
  {
    id: "ricotta-part-skim",
    name: "Ricotta, part-skim",
    category: "Eggs & dairy",
    proteinPer100g: 11.39,
    caloriesPer100g: 138,
    fatPer100g: 7.91,
    carbsPer100g: 5.14,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171248",
    fdcDataType: "SR Legacy",
  },
  {
    id: "nonfat-dry-milk-powder",
    name: "Nonfat dry milk (powder)",
    category: "Eggs & dairy",
    proteinPer100g: 36.16,
    caloriesPer100g: 362,
    fatPer100g: 0.77,
    carbsPer100g: 51.98,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170877",
    fdcDataType: "SR Legacy",
    note: "Dry powder (not reconstituted).",
  },
  {
    id: "kefir-lowfat",
    name: "Kefir, low-fat",
    category: "Eggs & dairy",
    proteinPer100g: 3.79,
    caloriesPer100g: 41,
    fatPer100g: 0.93,
    carbsPer100g: 4.48,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "170904",
    fdcDataType: "SR Legacy",
    note: "Plain, lowfat.",
  },
  {
    id: "skim-milk",
    name: "Skim milk",
    category: "Eggs & dairy",
    proteinPer100g: 3.37,
    caloriesPer100g: 34,
    fatPer100g: 0.08,
    carbsPer100g: 4.96,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.035,
    isCompleteProtein: true,
    fdcId: "171269",
    fdcDataType: "SR Legacy",
  },
  {
    id: "milk-2pct",
    name: "2% milk",
    category: "Eggs & dairy",
    proteinPer100g: 3.36,
    caloriesPer100g: 50,
    fatPer100g: 1.98,
    carbsPer100g: 4.9,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "171267",
    fdcDataType: "SR Legacy",
  },
  {
    id: "whole-milk",
    name: "Whole milk",
    category: "Eggs & dairy",
    proteinPer100g: 3.15,
    caloriesPer100g: 61,
    fatPer100g: 3.25,
    carbsPer100g: 4.8,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "171265",
    fdcDataType: "SR Legacy",
    note: "3.25% milkfat.",
  },
  {
    id: "buttermilk-lowfat",
    name: "Buttermilk, low-fat",
    category: "Eggs & dairy",
    proteinPer100g: 3.31,
    caloriesPer100g: 40,
    fatPer100g: 0.88,
    carbsPer100g: 4.79,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "170874",
    fdcDataType: "SR Legacy",
    note: "Cultured, lowfat.",
  },

  // ── Soy & plant (basis: as sold, except edamame cooked) ───────────────────
  {
    id: "tofu-firm",
    name: "Firm tofu",
    category: "Soy & plant",
    proteinPer100g: 9.04,
    caloriesPer100g: 78,
    fatPer100g: 4.17,
    carbsPer100g: 2.78,
    fiberPer100g: 0.9,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172448",
    fdcDataType: "SR Legacy",
    note: "Prepared with calcium sulfate and nigari.",
  },
  {
    id: "tofu-extra-firm",
    name: "Extra-firm tofu",
    category: "Soy & plant",
    proteinPer100g: 9.98,
    caloriesPer100g: 83,
    fatPer100g: 5.26,
    carbsPer100g: 1.18,
    fiberPer100g: 1.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174290",
    fdcDataType: "Foundation",
    note: "Prepared with nigari.",
  },
  {
    id: "tofu-silken",
    name: "Silken tofu",
    category: "Soy & plant",
    proteinPer100g: 7.17,
    caloriesPer100g: 61,
    fatPer100g: 3.69,
    carbsPer100g: 1.18,
    fiberPer100g: 0.2,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172449",
    fdcDataType: "SR Legacy",
    note: "USDA \"soft\" tofu.",
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "Soy & plant",
    proteinPer100g: 20.29,
    caloriesPer100g: 192,
    fatPer100g: 10.8,
    carbsPer100g: 7.64,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174272",
    fdcDataType: "SR Legacy",
    note: "USDA entry reports no dietary fiber value; actual tempeh contains fiber.",
  },
  {
    id: "edamame-shelled-cooked",
    name: "Edamame, shelled",
    category: "Soy & plant",
    proteinPer100g: 11.9,
    caloriesPer100g: 121,
    fatPer100g: 5.2,
    carbsPer100g: 8.9,
    fiberPer100g: 5.2,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168411",
    fdcDataType: "SR Legacy",
    note: "Frozen, prepared.",
  },
  {
    id: "soy-milk-unsweetened",
    name: "Soy milk, unsweetened",
    category: "Soy & plant",
    proteinPer100g: 2.9,
    caloriesPer100g: 33,
    fatPer100g: 1.6,
    carbsPer100g: 1.8,
    fiberPer100g: 0.5,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "175215",
    fdcDataType: "SR Legacy",
  },
  {
    id: "tvp-dry",
    name: "TVP (textured soy protein)",
    category: "Soy & plant",
    proteinPer100g: 58.1,
    caloriesPer100g: 331,
    fatPer100g: 0.5,
    carbsPer100g: 30.9,
    fiberPer100g: 5.5,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174301",
    fdcDataType: "SR Legacy",
    note: "Dry weight; rehydrates. USDA \"soy protein concentrate\" used as proxy; retail TVP protein varies (~50–67 g/100 g).",
  },

  // ── Legumes & grains (basis: cooked) ──────────────────────────────────────
  {
    id: "lentils-cooked",
    name: "Lentils",
    category: "Legumes & grains",
    proteinPer100g: 9.02,
    caloriesPer100g: 116,
    fatPer100g: 0.38,
    carbsPer100g: 20.13,
    fiberPer100g: 7.9,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "172421",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "black-beans-cooked",
    name: "Black beans",
    category: "Legumes & grains",
    proteinPer100g: 8.86,
    caloriesPer100g: 132,
    fatPer100g: 0.54,
    carbsPer100g: 23.71,
    fiberPer100g: 8.7,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "173735",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "chickpeas-cooked",
    name: "Chickpeas",
    category: "Legumes & grains",
    proteinPer100g: 8.86,
    caloriesPer100g: 164,
    fatPer100g: 2.59,
    carbsPer100g: 27.42,
    fiberPer100g: 7.6,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "173757",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "kidney-beans-cooked",
    name: "Kidney beans, red",
    category: "Legumes & grains",
    proteinPer100g: 8.67,
    caloriesPer100g: 127,
    fatPer100g: 0.5,
    carbsPer100g: 22.8,
    fiberPer100g: 6.4,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "175194",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "quinoa-cooked",
    name: "Quinoa",
    category: "Legumes & grains",
    proteinPer100g: 4.4,
    caloriesPer100g: 120,
    fatPer100g: 1.92,
    carbsPer100g: 21.3,
    fiberPer100g: 2.8,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168917",
    fdcDataType: "SR Legacy",
  },
  {
    id: "black-soybeans-cooked",
    name: "Black soybeans",
    category: "Legumes & grains",
    proteinPer100g: 18.2,
    caloriesPer100g: 172,
    fatPer100g: 9.0,
    carbsPer100g: 8.4,
    fiberPer100g: 6.0,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174271",
    fdcDataType: "SR Legacy",
    note: "USDA generic \"soybeans, cooked\" used (no separate black soybean entry).",
  },

  // ── Nuts & seeds (basis: as sold) ─────────────────────────────────────────
  {
    id: "peanut-butter",
    name: "Peanut butter",
    category: "Nuts & seeds",
    proteinPer100g: 22.5,
    caloriesPer100g: 588,
    fatPer100g: 49.9,
    carbsPer100g: 22.3,
    fiberPer100g: 5.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "174294",
    fdcDataType: "SR Legacy",
    note: "Smooth style, with salt.",
  },
  {
    id: "almonds",
    name: "Almonds",
    category: "Nuts & seeds",
    proteinPer100g: 21.15,
    caloriesPer100g: 579,
    fatPer100g: 49.93,
    carbsPer100g: 21.55,
    fiberPer100g: 12.5,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "170567",
    fdcDataType: "SR Legacy",
  },
  {
    id: "peanuts",
    name: "Peanuts",
    category: "Nuts & seeds",
    proteinPer100g: 25.8,
    caloriesPer100g: 567,
    fatPer100g: 49.24,
    carbsPer100g: 16.13,
    fiberPer100g: 8.5,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "172430",
    fdcDataType: "SR Legacy",
    note: "All types, raw.",
  },
  {
    id: "pumpkin-seeds",
    name: "Pumpkin seeds",
    category: "Nuts & seeds",
    proteinPer100g: 30.23,
    caloriesPer100g: 559,
    fatPer100g: 49.05,
    carbsPer100g: 10.71,
    fiberPer100g: 6.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "170556",
    fdcDataType: "SR Legacy",
    note: "Kernels, dried.",
  },
  {
    id: "hemp-seeds",
    name: "Hemp seeds",
    category: "Nuts & seeds",
    proteinPer100g: 31.56,
    caloriesPer100g: 553,
    fatPer100g: 48.75,
    carbsPer100g: 8.67,
    fiberPer100g: 4.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170148",
    fdcDataType: "SR Legacy",
    note: "Hulled. Hemp is a complete protein (spec §7).",
  },
  {
    id: "chia-seeds",
    name: "Chia seeds",
    category: "Nuts & seeds",
    proteinPer100g: 16.54,
    caloriesPer100g: 486,
    fatPer100g: 30.74,
    carbsPer100g: 42.12,
    fiberPer100g: 34.4,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "170554",
    fdcDataType: "SR Legacy",
    note: "Dried.",
  },
  {
    id: "almond-butter",
    name: "Almond butter",
    category: "Nuts & seeds",
    proteinPer100g: 20.96,
    caloriesPer100g: 614,
    fatPer100g: 55.5,
    carbsPer100g: 18.82,
    fiberPer100g: 10.3,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "168588",
    fdcDataType: "SR Legacy",
    note: "Plain, without salt added.",
  },

  // ── Protein powders & supplements (basis: as sold) ────────────────────────
  {
    id: "whey-protein-isolate",
    name: "Whey protein isolate",
    category: "Protein powders",
    proteinPer100g: 90.9,
    caloriesPer100g: 377,
    fatPer100g: 1.5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "2413194",
    fdcDataType: "Branded",
    note: POWDER_NOTE,
  },
  {
    id: "whey-protein-concentrate",
    name: "Whey protein concentrate",
    category: "Protein powders",
    proteinPer100g: 75.8,
    caloriesPer100g: 396,
    fatPer100g: 7.6,
    carbsPer100g: 6.1,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "2413184",
    fdcDataType: "Branded",
    note: POWDER_NOTE,
  },
  {
    id: "casein-protein",
    name: "Casein protein",
    category: "Protein powders",
    proteinPer100g: 78.1,
    caloriesPer100g: 325,
    fatPer100g: 0,
    carbsPer100g: 3.1,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "2593012",
    fdcDataType: "Branded",
    note: POWDER_NOTE,
  },
  {
    id: "pea-protein-isolate",
    name: "Pea protein isolate",
    category: "Protein powders",
    proteinPer100g: 80.0,
    caloriesPer100g: 400,
    fatPer100g: 7.0,
    carbsPer100g: 6.0,
    fiberPer100g: 5.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "2174902",
    fdcDataType: "Branded",
    note: POWDER_NOTE + " Pea is lower in methionine (spec §7 treats single legumes as incomplete).",
  },
  {
    id: "soy-protein-isolate",
    name: "Soy protein isolate",
    category: "Protein powders",
    proteinPer100g: 88.32,
    caloriesPer100g: 335,
    fatPer100g: 3.39,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174276",
    fdcDataType: "SR Legacy",
    note: POWDER_NOTE + " Some references cite ~80.7 g protein / ~7.4 g carb.",
  },
  {
    id: "egg-white-protein",
    name: "Egg white protein",
    category: "Protein powders",
    proteinPer100g: 81.1,
    caloriesPer100g: 382,
    fatPer100g: 0,
    carbsPer100g: 7.8,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172204",
    fdcDataType: "SR Legacy",
    note: POWDER_NOTE + " USDA \"egg, white, dried\".",
  },
  {
    id: "collagen-peptides",
    name: "Collagen peptides",
    category: "Protein powders",
    proteinPer100g: 90.0,
    caloriesPer100g: 360,
    fatPer100g: 0,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "1045127",
    fdcDataType: "Branded",
    note: "Incomplete protein (spec §7): collagen does not count toward a complete-protein meal. " + POWDER_NOTE,
  },

  // ── Broths & liquids ──────────────────────────────────────────────────────
  {
    id: "bone-broth",
    name: "Bone broth",
    category: "Broths & liquids",
    proteinPer100g: 4.17,
    caloriesPer100g: 19,
    fatPer100g: 0,
    carbsPer100g: 0.42,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.0,
    isCompleteProtein: true,
    fdcId: "2527261",
    fdcDataType: "Branded",
    note: "High-protein bone broth (Branded); protein is brand-dependent.",
  },
];

// Attach per-100g micronutrients (lib/micros.ts) to each food by id.
export const FOODS: Food[] = FOOD_BASE.map((f) => {
  const micros = MICROS[f.id];
  if (!micros) {
    throw new Error(`Dataset error: no micros for "${f.id}" (see lib/micros.ts).`);
  }
  return { ...f, micros };
});

// Enforce dataset integrity at import (build) time (spec §10 + §A caloriesPer100g).
validateDataset(FOODS);
