import type { Food } from "./types";
import { validateDataset } from "./compute";
import { MICROS } from "./micros";

/**
 * Baked-in nutrition dataset (spec §Data). Values are per 100 g, sourced from USDA
 * FoodData Central (Foundation Foods and SR Legacy where available; a few Branded
 * entries only where no generic exists). Every food records its source `fdcId` and
 * `fdcDataType` so each number is traceable. The client bundle contains no API key
 * and makes no nutrition calls.
 *
 * v4 is TRIMMED to dinner anchors: Nuts & seeds, Protein powders, and Broths &
 * liquids are dropped, and Eggs & dairy keeps only the dinner-relevant items (eggs,
 * cottage cheese, Greek yogurt, plus the grill/pan cheeses halloumi and paneer).
 * Lamb, Goat, and Game (wild boar, venison, bison) are their own categories. ~68 foods.
 *
 * COOKED BASIS (spec §"Raw vs cooked"): muscle meats and fish stored raw carry
 * parallel cooked fields (proteinPer100gCooked / caloriesPer100gCooked + optional
 * cooked macros + a cooked fdcId) from real FDC "cooked, roasted" / "cooked, dry
 * heat" records — never a raw→cooked multiplier. These cooked values are UNVERIFIED
 * in this environment (no FDC key / no network to FDC); every one is listed in
 * COOKED_VALUES.md and must be confirmed with:
 *   FDC_API_KEY=your_key npm run build:data
 * (see scripts/build-dataset.ts). The key is build-time only and never ships.
 *
 * weightBasis is per-category (spec §5): raw for muscle meats/fish, cooked for
 * legumes/grains, as sold for dairy/eggs/tofu/canned/cured. Liquid densities (g/mL)
 * are approximate (spec §6) and used only for the fl-oz conversion.
 */

// Macro/metadata rows. Per-100g micronutrients live in lib/micros.ts (keyed by id)
// and are attached below, so this array stays readable and the two concerns can be
// refreshed independently by the build job.
const FOOD_BASE: Omit<Food, "micros">[] = [
  // ── Poultry (basis: raw; cooked = roasted, meat only unless noted) ─────────
  {
    id: "chicken-breast-skinless-raw",
    name: "Chicken breast, skinless",
    category: "Poultry",
    proteinPer100g: 22.5,
    caloriesPer100g: 120,
    fatPer100g: 2.62,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171077",
    fdcDataType: "SR Legacy",
    note: "Meat only.",
    proteinPer100gCooked: 31.02,
    caloriesPer100gCooked: 165,
    fatPer100gCooked: 3.57,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171534",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "chicken-thigh-skinless-raw",
    name: "Chicken thigh, skinless",
    category: "Poultry",
    proteinPer100g: 19.66,
    caloriesPer100g: 121,
    fatPer100g: 4.14,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173627",
    fdcDataType: "SR Legacy",
    note: "Meat only. FDC also has a fattier boneless-skinless-thigh entry (2646171) — verify via build:data.",
    proteinPer100gCooked: 26.0,
    caloriesPer100gCooked: 209,
    fatPer100gCooked: 10.9,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172863",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "chicken-thigh-skin-on-raw",
    name: "Chicken thigh, skin-on",
    category: "Poultry",
    proteinPer100g: 16.52,
    caloriesPer100g: 221,
    fatPer100g: 16.61,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172385",
    fdcDataType: "SR Legacy",
    note: "Meat and skin.",
    proteinPer100gCooked: 23.55,
    caloriesPer100gCooked: 247,
    fatPer100gCooked: 15.53,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172852",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "chicken-drumstick-skinless-raw",
    name: "Chicken drumstick, skinless",
    category: "Poultry",
    proteinPer100g: 20.59,
    caloriesPer100g: 119,
    fatPer100g: 3.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173614",
    fdcDataType: "SR Legacy",
    note: "Meat only.",
    proteinPer100gCooked: 24.24,
    caloriesPer100gCooked: 155,
    fatPer100gCooked: 5.71,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172861",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "chicken-wing-raw",
    name: "Chicken wing",
    category: "Poultry",
    proteinPer100g: 17.5,
    caloriesPer100g: 191,
    fatPer100g: 12.8,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172390",
    fdcDataType: "SR Legacy",
    note: "Meat and skin.",
    proteinPer100gCooked: 30.46,
    caloriesPer100gCooked: 290,
    fatPer100gCooked: 19.49,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172854",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "ground-chicken-93-7-raw",
    name: "Ground chicken, 93/7",
    category: "Poultry",
    proteinPer100g: 19.6,
    caloriesPer100g: 150,
    fatPer100g: 6.3,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "2278952",
    fdcDataType: "Branded",
    note: "Brand-dependent (93/7); USDA has no generic 93/7 entry. Generic SR Legacy ground chicken is ≈143 kcal / 17.4 g protein.",
    proteinPer100gCooked: 27.1,
    caloriesPer100gCooked: 189,
    fatPer100gCooked: 8.9,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "2646174",
    fdcDataTypeCooked: "Branded",
  },
  {
    id: "turkey-breast-skinless-raw",
    name: "Turkey breast, skinless",
    category: "Poultry",
    proteinPer100g: 19.8,
    caloriesPer100g: 97,
    fatPer100g: 1.98,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174515",
    fdcDataType: "SR Legacy",
    note: "Retail parts, meat only.",
    proteinPer100gCooked: 29.55,
    caloriesPer100gCooked: 135,
    fatPer100gCooked: 0.74,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171496",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "ground-turkey-93-7-raw",
    name: "Ground turkey, 93/7",
    category: "Poultry",
    proteinPer100g: 18.73,
    caloriesPer100g: 150,
    fatPer100g: 8.34,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172850",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 27.37,
    caloriesPer100gCooked: 203,
    fatPer100gCooked: 10.4,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172856",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "duck-breast-raw",
    name: "Duck breast, skinless",
    category: "Poultry",
    proteinPer100g: 18.28,
    caloriesPer100g: 135,
    fatPer100g: 5.95,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172410",
    fdcDataType: "SR Legacy",
    note: "USDA \"duck, domesticated, meat only, raw\" (all cuts).",
    proteinPer100gCooked: 23.48,
    caloriesPer100gCooked: 201,
    fatPer100gCooked: 11.2,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172413",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "duck-leg-skin-on-raw",
    name: "Duck leg, skin-on",
    category: "Poultry",
    proteinPer100g: 11.49,
    caloriesPer100g: 404,
    fatPer100g: 39.34,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172409",
    fdcDataType: "SR Legacy",
    note: "USDA has no discrete duck-leg cut; \"duck, meat and skin, raw\" (whole bird, skin-on) is used as a proxy for the skin-on leg (the form legs are usually cooked). Fatty by nature. UNVERIFIED (no FDC access here) — confirm with `FDC_API_KEY=... npm run build:data`.",
    proteinPer100gCooked: 19.0,
    caloriesPer100gCooked: 337,
    fatPer100gCooked: 28.35,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172412",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Pork (basis: raw, except cured; cooked = roasted, lean) ────────────────
  {
    id: "pork-tenderloin-raw",
    name: "Pork tenderloin",
    category: "Pork",
    proteinPer100g: 20.95,
    caloriesPer100g: 109,
    fatPer100g: 2.17,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168249",
    fdcDataType: "SR Legacy",
    note: "Separable lean only.",
    proteinPer100gCooked: 26.17,
    caloriesPer100gCooked: 143,
    fatPer100gCooked: 3.51,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "168251",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "pork-loin-chop-raw",
    name: "Pork loin chop",
    category: "Pork",
    proteinPer100g: 21.9,
    caloriesPer100g: 127,
    fatPer100g: 3.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168237",
    fdcDataType: "SR Legacy",
    note: "Center loin, separable lean only; fdcId inferred — verify via build:data.",
    proteinPer100gCooked: 27.1,
    caloriesPer100gCooked: 175,
    fatPer100gCooked: 6.3,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "168238",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "pork-shoulder-raw",
    name: "Pork shoulder",
    category: "Pork",
    proteinPer100g: 17.3,
    caloriesPer100g: 236,
    fatPer100g: 18.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "167843",
    fdcDataType: "SR Legacy",
    note: "Whole, separable lean and fat.",
    proteinPer100gCooked: 24.65,
    caloriesPer100gCooked: 269,
    fatPer100gCooked: 18.1,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "167844",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "ground-pork-raw",
    name: "Ground pork",
    category: "Pork",
    proteinPer100g: 16.88,
    caloriesPer100g: 263,
    fatPer100g: 21.19,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "167902",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 25.69,
    caloriesPer100gCooked: 297,
    fatPer100gCooked: 20.77,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "167903",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "bacon-raw",
    name: "Bacon",
    category: "Pork",
    proteinPer100g: 12.62,
    caloriesPer100g: 417,
    fatPer100g: 39.69,
    carbsPer100g: 1.28,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168277",
    fdcDataType: "SR Legacy",
    note: "Cured, unprepared — high fat, will surface as inefficient (kept intentionally). Weigh as sold.",
  },
  {
    id: "ham-cured-as-sold",
    name: "Ham, sliced (cured)",
    category: "Pork",
    proteinPer100g: 16.6,
    caloriesPer100g: 163,
    fatPer100g: 8.6,
    carbsPer100g: 3.83,
    fiberPer100g: 1.3,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173864",
    fdcDataType: "SR Legacy",
    note: "Regular, ~11% fat, cured/cooked. Listed fiber (1.3 g) reflects added ingredients.",
  },

  // ── Beef (basis: raw; cooked = broiled/braised, lean) ──────────────────────
  {
    id: "ground-beef-90-10-raw",
    name: "Ground beef, 90/10",
    category: "Beef",
    proteinPer100g: 20.0,
    caloriesPer100g: 176,
    fatPer100g: 10.0,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174030",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 25.8,
    caloriesPer100gCooked: 217,
    fatPer100gCooked: 11.7,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174034",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "ground-beef-80-20-raw",
    name: "Ground beef, 80/20",
    category: "Beef",
    proteinPer100g: 17.17,
    caloriesPer100g: 254,
    fatPer100g: 20.0,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174036",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 25.75,
    caloriesPer100gCooked: 254,
    fatPer100gCooked: 15.41,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174037",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-top-sirloin-raw",
    name: "Top sirloin, lean",
    category: "Beef",
    proteinPer100g: 22.1,
    caloriesPer100g: 131,
    fatPer100g: 4.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174055",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
    proteinPer100gCooked: 29.4,
    caloriesPer100gCooked: 194,
    fatPer100gCooked: 6.79,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174056",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-ribeye-raw",
    name: "Ribeye, lean",
    category: "Beef",
    proteinPer100g: 21.9,
    caloriesPer100g: 154,
    fatPer100g: 7.4,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172143",
    fdcDataType: "SR Legacy",
    note: "Boneless, lip-off, separable lean only.",
    proteinPer100gCooked: 27.9,
    caloriesPer100gCooked: 213,
    fatPer100gCooked: 10.2,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172144",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-flank-raw",
    name: "Flank steak, lean",
    category: "Beef",
    proteinPer100g: 21.72,
    caloriesPer100g: 143,
    fatPer100g: 6.29,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174776",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 0\" fat.",
    proteinPer100gCooked: 28.5,
    caloriesPer100gCooked: 192,
    fatPer100gCooked: 7.48,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174777",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-chuck-raw",
    name: "Chuck, lean",
    category: "Beef",
    proteinPer100g: 21.96,
    caloriesPer100g: 139,
    fatPer100g: 5.05,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174051",
    fdcDataType: "SR Legacy",
    note: "Arm pot roast, separable lean only.",
    proteinPer100gCooked: 30.5,
    caloriesPer100gCooked: 213,
    fatPer100gCooked: 9.2,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174052",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-tenderloin-raw",
    name: "Tenderloin, lean",
    category: "Beef",
    proteinPer100g: 22.12,
    caloriesPer100g: 153,
    fatPer100g: 6.52,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171812",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
    proteinPer100gCooked: 28.2,
    caloriesPer100gCooked: 207,
    fatPer100gCooked: 9.3,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171813",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "beef-top-round-raw",
    name: "Top round, lean",
    category: "Beef",
    proteinPer100g: 22.9,
    caloriesPer100g: 135,
    fatPer100g: 4.03,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171816",
    fdcDataType: "SR Legacy",
    note: "Separable lean only, trimmed to 1/8\" fat.",
    proteinPer100gCooked: 30.9,
    caloriesPer100gCooked: 202,
    fatPer100gCooked: 6.63,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171817",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "veal-leg-top-round-raw",
    name: "Veal, leg (top round)",
    category: "Beef",
    proteinPer100g: 20.72,
    caloriesPer100g: 107,
    fatPer100g: 2.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174320",
    fdcDataType: "SR Legacy",
    note: "Separable lean only. Cooked = braised, lean. UNVERIFIED (no FDC access here) — confirm with `FDC_API_KEY=... npm run build:data`.",
    proteinPer100gCooked: 31.9,
    caloriesPer100gCooked: 172,
    fatPer100gCooked: 4.34,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174321",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Lamb (basis: raw; cooked = roasted/broiled/braised, lean) ──────────────
  // Muscle-meat macros + cooked records compiled from USDA SR Legacy lamb entries;
  // UNVERIFIED here (no FDC access). Confirm with `FDC_API_KEY=... npm run build:data`.
  {
    id: "lamb-leg-raw",
    name: "Lamb, leg",
    category: "Lamb",
    proteinPer100g: 20.56,
    caloriesPer100g: 134,
    fatPer100g: 5.71,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172542",
    fdcDataType: "SR Legacy",
    note: "Whole leg (shank + sirloin), separable lean only. Cooked = roasted, lean.",
    proteinPer100gCooked: 28.18,
    caloriesPer100gCooked: 191,
    fatPer100gCooked: 8.79,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172543",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "lamb-shoulder-raw",
    name: "Lamb, shoulder",
    category: "Lamb",
    proteinPer100g: 16.94,
    caloriesPer100g: 162,
    fatPer100g: 9.8,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172554",
    fdcDataType: "SR Legacy",
    note: "Whole shoulder (arm + blade), separable lean only. Cooked = braised, lean.",
    proteinPer100gCooked: 28.6,
    caloriesPer100gCooked: 259,
    fatPer100gCooked: 15.3,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172555",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "lamb-loin-chop-raw",
    name: "Lamb loin chop",
    category: "Lamb",
    proteinPer100g: 19.32,
    caloriesPer100g: 148,
    fatPer100g: 7.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172524",
    fdcDataType: "SR Legacy",
    note: "Loin, separable lean only. Cooked = broiled, lean.",
    proteinPer100gCooked: 28.83,
    caloriesPer100gCooked: 215,
    fatPer100gCooked: 9.74,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "172525",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "lamb-ground-raw",
    name: "Ground lamb",
    category: "Lamb",
    proteinPer100g: 16.56,
    caloriesPer100g: 282,
    fatPer100g: 23.41,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174389",
    fdcDataType: "SR Legacy",
    note: "Cooked = broiled.",
    proteinPer100gCooked: 25.03,
    caloriesPer100gCooked: 283,
    fatPer100gCooked: 19.66,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174390",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Goat (basis: raw; cooked = roasted) ────────────────────────────────────
  {
    id: "goat-raw",
    name: "Goat",
    category: "Goat",
    proteinPer100g: 20.6,
    caloriesPer100g: 109,
    fatPer100g: 2.31,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174379",
    fdcDataType: "SR Legacy",
    note: "USDA \"Game meat, goat, raw\" (sold as generic/cubed goat meat). Cooked = roasted. UNVERIFIED (no FDC access here) — confirm with `FDC_API_KEY=... npm run build:data`.",
    proteinPer100gCooked: 27.1,
    caloriesPer100gCooked: 143,
    fatPer100gCooked: 3.03,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174380",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Game (basis: raw; cooked = roasted/pan-broiled, lean) ──────────────────
  // USDA "Game meat, …" SR Legacy entries; UNVERIFIED here (no FDC access).
  {
    id: "boar-wild-raw",
    name: "Wild boar",
    category: "Game",
    proteinPer100g: 21.51,
    caloriesPer100g: 122,
    fatPer100g: 3.33,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174384",
    fdcDataType: "SR Legacy",
    note: "USDA \"Game meat, boar, wild, raw\". Cooked = roasted.",
    proteinPer100gCooked: 28.29,
    caloriesPer100gCooked: 160,
    fatPer100gCooked: 4.38,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174385",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "venison-deer-raw",
    name: "Venison (deer)",
    category: "Game",
    proteinPer100g: 22.96,
    caloriesPer100g: 120,
    fatPer100g: 2.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174375",
    fdcDataType: "SR Legacy",
    note: "USDA \"Game meat, deer, raw\". Cooked = roasted.",
    proteinPer100gCooked: 30.21,
    caloriesPer100gCooked: 158,
    fatPer100gCooked: 3.19,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174376",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "bison-lean-raw",
    name: "Bison, lean",
    category: "Game",
    proteinPer100g: 21.62,
    caloriesPer100g: 109,
    fatPer100g: 1.83,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174372",
    fdcDataType: "SR Legacy",
    note: "USDA \"Game meat, bison, separable lean only, raw\" (roast/steak). Cooked = roasted, lean.",
    proteinPer100gCooked: 28.44,
    caloriesPer100gCooked: 143,
    fatPer100gCooked: 2.42,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174373",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Seafood (basis: raw, except canned; cooked = dry/moist heat) ───────────
  {
    id: "salmon-atlantic-farmed-raw",
    name: "Salmon, Atlantic (farmed)",
    category: "Seafood",
    proteinPer100g: 20.42,
    caloriesPer100g: 208,
    fatPer100g: 13.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175167",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 25.44,
    caloriesPer100gCooked: 206,
    fatPer100gCooked: 12.35,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "175168",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "salmon-sockeye-wild-raw",
    name: "Salmon, sockeye (wild)",
    category: "Seafood",
    proteinPer100g: 22.25,
    caloriesPer100g: 131,
    fatPer100g: 4.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173691",
    fdcDataType: "SR Legacy",
    note: "FDC entry is \"salmon, sockeye, raw\"; sockeye is wild-caught.",
    proteinPer100gCooked: 26.48,
    caloriesPer100gCooked: 156,
    fatPer100gCooked: 4.99,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "173692",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "tuna-yellowfin-raw",
    name: "Tuna, yellowfin",
    category: "Seafood",
    proteinPer100g: 24.4,
    caloriesPer100g: 109,
    fatPer100g: 0.49,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175159",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 29.15,
    caloriesPer100gCooked: 139,
    fatPer100gCooked: 1.22,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "175160",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "tuna-canned-water-drained",
    name: "Tuna, canned in water",
    category: "Seafood",
    proteinPer100g: 25.51,
    caloriesPer100g: 116,
    fatPer100g: 0.82,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173709",
    fdcDataType: "SR Legacy",
    note: "Light, canned in water, drained solids.",
  },
  {
    id: "cod-atlantic-raw",
    name: "Cod, Atlantic",
    category: "Seafood",
    proteinPer100g: 17.81,
    caloriesPer100g: 82,
    fatPer100g: 0.67,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171955",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 22.83,
    caloriesPer100gCooked: 105,
    fatPer100gCooked: 0.86,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171956",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "tilapia-raw",
    name: "Tilapia",
    category: "Seafood",
    proteinPer100g: 20.08,
    caloriesPer100g: 96,
    fatPer100g: 1.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175176",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 26.15,
    caloriesPer100gCooked: 128,
    fatPer100gCooked: 2.65,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "175177",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "shrimp-raw",
    name: "Shrimp",
    category: "Seafood",
    proteinPer100g: 13.61,
    caloriesPer100g: 71,
    fatPer100g: 1.01,
    carbsPer100g: 0.91,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "15149",
    fdcDataType: "SR Legacy",
    note: "Mixed species; current FDC entry reflects moisture-retention additives, so protein reads lower than plain shrimp.",
    proteinPer100gCooked: 24.0,
    caloriesPer100gCooked: 99,
    fatPer100gCooked: 0.28,
    carbsPer100gCooked: 0.2,
    fiberPer100gCooked: 0,
    fdcIdCooked: "171992",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "halibut-raw",
    name: "Halibut",
    category: "Seafood",
    proteinPer100g: 18.56,
    caloriesPer100g: 91,
    fatPer100g: 1.33,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174200",
    fdcDataType: "SR Legacy",
    note: "Atlantic and Pacific.",
    proteinPer100gCooked: 26.69,
    caloriesPer100gCooked: 140,
    fatPer100gCooked: 2.96,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174201",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "sardines-canned-oil-drained",
    name: "Sardines, canned in oil",
    category: "Seafood",
    proteinPer100g: 24.62,
    caloriesPer100g: 208,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175139",
    fdcDataType: "SR Legacy",
    note: "Atlantic, drained solids with bone.",
  },
  {
    id: "mackerel-atlantic-raw",
    name: "Mackerel, Atlantic",
    category: "Seafood",
    proteinPer100g: 18.6,
    caloriesPer100g: 205,
    fatPer100g: 13.89,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "175119",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 23.85,
    caloriesPer100gCooked: 262,
    fatPer100gCooked: 17.81,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "175120",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "rainbow-trout-farmed-raw",
    name: "Rainbow trout (farmed)",
    category: "Seafood",
    proteinPer100g: 19.94,
    caloriesPer100g: 141,
    fatPer100g: 6.18,
    carbsPer100g: 0,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173717",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 24.27,
    caloriesPer100gCooked: 168,
    fatPer100gCooked: 7.2,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "173718",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "scallops-raw",
    name: "Scallops",
    category: "Seafood",
    proteinPer100g: 12.06,
    caloriesPer100g: 69,
    fatPer100g: 0.49,
    carbsPer100g: 3.18,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174220",
    fdcDataType: "SR Legacy",
    note: "Mixed species.",
    proteinPer100gCooked: 20.54,
    caloriesPer100gCooked: 111,
    fatPer100gCooked: 0.84,
    carbsPer100gCooked: 5.41,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174221",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "mussels-raw",
    name: "Mussels, blue",
    category: "Seafood",
    proteinPer100g: 11.9,
    caloriesPer100g: 86,
    fatPer100g: 2.24,
    carbsPer100g: 3.69,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174216",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 23.8,
    caloriesPer100gCooked: 172,
    fatPer100gCooked: 4.48,
    carbsPer100gCooked: 7.39,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174217",
    fdcDataTypeCooked: "SR Legacy",
  },
  {
    id: "crab-raw",
    name: "Crab, blue",
    category: "Seafood",
    proteinPer100g: 18.06,
    caloriesPer100g: 87,
    fatPer100g: 0.92,
    carbsPer100g: 0.04,
    fiberPer100g: 0,
    weightBasis: "raw",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174204",
    fdcDataType: "SR Legacy",
    proteinPer100gCooked: 20.2,
    caloriesPer100gCooked: 100,
    fatPer100gCooked: 1.77,
    carbsPer100gCooked: 0,
    fiberPer100gCooked: 0,
    fdcIdCooked: "174205",
    fdcDataTypeCooked: "SR Legacy",
  },

  // ── Eggs & dairy (dinner-relevant only: eggs, cottage cheese, Greek yogurt) ─
  {
    id: "whole-egg",
    name: "Whole egg",
    category: "Eggs & dairy",
    proteinPer100g: 12.56,
    caloriesPer100g: 143,
    fatPer100g: 9.51,
    carbsPer100g: 0.72,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "171287",
    fdcDataType: "SR Legacy",
  },
  {
    id: "egg-white-liquid",
    name: "Egg white (liquid)",
    category: "Eggs & dairy",
    proteinPer100g: 10.9,
    caloriesPer100g: 52,
    fatPer100g: 0.17,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.04,
    isCompleteProtein: true,
    fdcId: "172183",
    fdcDataType: "SR Legacy",
  },
  {
    id: "greek-yogurt-nonfat",
    name: "Greek yogurt, nonfat",
    category: "Eggs & dairy",
    proteinPer100g: 10.19,
    caloriesPer100g: 59,
    fatPer100g: 0.39,
    carbsPer100g: 3.6,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170894",
    fdcDataType: "SR Legacy",
  },
  {
    id: "greek-yogurt-2pct",
    name: "Greek yogurt, 2%",
    category: "Eggs & dairy",
    proteinPer100g: 9.95,
    caloriesPer100g: 73,
    fatPer100g: 1.92,
    carbsPer100g: 3.94,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "170903",
    fdcDataType: "SR Legacy",
    note: "USDA \"lowfat\" Greek yogurt (~1.9% milkfat).",
  },
  {
    id: "cottage-cheese-lowfat",
    name: "Cottage cheese, low-fat",
    category: "Eggs & dairy",
    proteinPer100g: 12.39,
    caloriesPer100g: 72,
    fatPer100g: 1.02,
    carbsPer100g: 2.72,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "173417",
    fdcDataType: "SR Legacy",
    note: "1% milkfat.",
  },
  {
    id: "cottage-cheese-fullfat",
    name: "Cottage cheese, full-fat",
    category: "Eggs & dairy",
    proteinPer100g: 11.12,
    caloriesPer100g: 98,
    fatPer100g: 4.3,
    carbsPer100g: 3.38,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172179",
    fdcDataType: "SR Legacy",
    note: "Creamed, large or small curd.",
  },
  {
    id: "halloumi",
    name: "Halloumi",
    category: "Eggs & dairy",
    proteinPer100g: 22,
    caloriesPer100g: 321,
    fatPer100g: 26,
    carbsPer100g: 2.2,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "473542",
    fdcDataType: "Branded",
    note: "Grilling/pan-frying cheese (dinner protein). Values compiled from a USDA FDC Branded halloumi record and typical brand data; UNVERIFIED in this build environment (no FDC_API_KEY / no network to FDC). Halloumi differs by brand (protein ~20–25 g, calcium ~600–900 mg per 100 g). Confirm with `FDC_API_KEY=... npm run build:data`.",
  },
  {
    id: "paneer",
    name: "Paneer",
    category: "Eggs & dairy",
    proteinPer100g: 18.3,
    caloriesPer100g: 265,
    fatPer100g: 20.8,
    carbsPer100g: 3.4,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "426090",
    fdcDataType: "Branded",
    note: "Fresh Indian cheese (pan-fried/curried as a dinner protein). Values compiled from USDA FDC Branded paneer and typical brand data; UNVERIFIED in this build environment (no FDC_API_KEY / no network to FDC). Varies by brand (protein ~18–20 g, fat ~20–25 g per 100 g). Confirm with `FDC_API_KEY=... npm run build:data`.",
  },

  // ── Soy & plant (basis: as sold, except edamame cooked) ────────────────────
  {
    id: "tofu-firm",
    name: "Firm tofu",
    category: "Soy & plant",
    proteinPer100g: 9.04,
    caloriesPer100g: 78,
    fatPer100g: 4.17,
    carbsPer100g: 2.78,
    fiberPer100g: 0.9,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172448",
    fdcDataType: "SR Legacy",
    note: "Prepared with calcium sulfate and nigari.",
  },
  {
    id: "tofu-extra-firm",
    name: "Extra-firm tofu",
    category: "Soy & plant",
    proteinPer100g: 9.98,
    caloriesPer100g: 83,
    fatPer100g: 5.26,
    carbsPer100g: 1.18,
    fiberPer100g: 1.0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174290",
    fdcDataType: "Foundation",
    note: "Prepared with nigari.",
  },
  {
    id: "tofu-silken",
    name: "Silken tofu",
    category: "Soy & plant",
    proteinPer100g: 7.17,
    caloriesPer100g: 61,
    fatPer100g: 3.69,
    carbsPer100g: 1.18,
    fiberPer100g: 0.2,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "172449",
    fdcDataType: "SR Legacy",
    note: "USDA \"soft\" tofu.",
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "Soy & plant",
    proteinPer100g: 20.29,
    caloriesPer100g: 192,
    fatPer100g: 10.8,
    carbsPer100g: 7.64,
    fiberPer100g: 0,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174272",
    fdcDataType: "SR Legacy",
    note: "USDA entry reports no dietary fiber value; actual tempeh contains fiber.",
  },
  {
    id: "edamame-shelled-cooked",
    name: "Edamame, shelled",
    category: "Soy & plant",
    proteinPer100g: 11.9,
    caloriesPer100g: 121,
    fatPer100g: 5.2,
    carbsPer100g: 8.9,
    fiberPer100g: 5.2,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168411",
    fdcDataType: "SR Legacy",
    note: "Frozen, prepared.",
  },
  {
    id: "soy-milk-unsweetened",
    name: "Soy milk, unsweetened",
    category: "Soy & plant",
    proteinPer100g: 2.9,
    caloriesPer100g: 33,
    fatPer100g: 1.6,
    carbsPer100g: 1.8,
    fiberPer100g: 0.5,
    weightBasis: "as_sold",
    isLiquid: true,
    densityGPerMl: 1.03,
    isCompleteProtein: true,
    fdcId: "175215",
    fdcDataType: "SR Legacy",
  },
  {
    id: "tvp-dry",
    name: "TVP (textured soy protein)",
    category: "Soy & plant",
    proteinPer100g: 58.1,
    caloriesPer100g: 331,
    fatPer100g: 0.5,
    carbsPer100g: 30.9,
    fiberPer100g: 5.5,
    weightBasis: "as_sold",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174301",
    fdcDataType: "SR Legacy",
    note: "Dry weight; rehydrates. USDA \"soy protein concentrate\" used as proxy; retail TVP protein varies (~50–67 g/100 g).",
  },

  // ── Legumes & grains (basis: cooked, as eaten; toggle is a no-op) ──────────
  {
    id: "lentils-cooked",
    name: "Lentils",
    category: "Legumes & grains",
    proteinPer100g: 9.02,
    caloriesPer100g: 116,
    fatPer100g: 0.38,
    carbsPer100g: 20.13,
    fiberPer100g: 7.9,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "172421",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "black-beans-cooked",
    name: "Black beans",
    category: "Legumes & grains",
    proteinPer100g: 8.86,
    caloriesPer100g: 132,
    fatPer100g: 0.54,
    carbsPer100g: 23.71,
    fiberPer100g: 8.7,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "173735",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "chickpeas-cooked",
    name: "Chickpeas",
    category: "Legumes & grains",
    proteinPer100g: 8.86,
    caloriesPer100g: 164,
    fatPer100g: 2.59,
    carbsPer100g: 27.42,
    fiberPer100g: 7.6,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "173757",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "kidney-beans-cooked",
    name: "Kidney beans, red",
    category: "Legumes & grains",
    proteinPer100g: 8.67,
    caloriesPer100g: 127,
    fatPer100g: 0.5,
    carbsPer100g: 22.8,
    fiberPer100g: 6.4,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: false,
    fdcId: "175194",
    fdcDataType: "SR Legacy",
    note: "Cooked, boiled, without salt.",
  },
  {
    id: "quinoa-cooked",
    name: "Quinoa",
    category: "Legumes & grains",
    proteinPer100g: 4.4,
    caloriesPer100g: 120,
    fatPer100g: 1.92,
    carbsPer100g: 21.3,
    fiberPer100g: 2.8,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "168917",
    fdcDataType: "SR Legacy",
  },
  {
    id: "black-soybeans-cooked",
    name: "Black soybeans",
    category: "Legumes & grains",
    proteinPer100g: 18.2,
    caloriesPer100g: 172,
    fatPer100g: 9.0,
    carbsPer100g: 8.4,
    fiberPer100g: 6.0,
    weightBasis: "cooked",
    isLiquid: false,
    isCompleteProtein: true,
    fdcId: "174271",
    fdcDataType: "SR Legacy",
    note: "USDA generic \"soybeans, cooked\" used (no separate black soybean entry).",
  },
];

// Attach per-100g micronutrients (lib/micros.ts) to each food by id.
export const FOODS: Food[] = FOOD_BASE.map((f) => {
  const micros = MICROS[f.id];
  if (!micros) {
    throw new Error(`Dataset error: no micros for "${f.id}" (see lib/micros.ts).`);
  }
  return { ...f, micros };
});

// Enforce dataset integrity at import (build) time (spec §10 + §A caloriesPer100g).
validateDataset(FOODS);
